"""Static family-name -> category lookup, keyed by Google Fonts metadata categories.

fontTools cannot reliably derive serif/sans/slab/mono/display from glyph outlines,
so this table is hand-curated from Google Fonts' own category tags for the fonts
this project downloads. Extend it as new families are added to fonts/.
"""

FAMILY_CATEGORY = {
    "Roboto": "sans-serif",
    "Open Sans": "sans-serif",
    "Lato": "sans-serif",
    "Montserrat": "sans-serif",
    "Source Sans Pro": "sans-serif",
    "Source Sans 3": "sans-serif",
    "Poppins": "sans-serif",
    "Nunito": "sans-serif",
    "Nunito Sans": "sans-serif",
    "Raleway": "sans-serif",
    "Inter": "sans-serif",
    "Work Sans": "sans-serif",
    "Rubik": "sans-serif",
    "Mulish": "sans-serif",
    "Karla": "sans-serif",
    "Barlow": "sans-serif",
    "Manrope": "sans-serif",
    "Heebo": "sans-serif",
    "DM Sans": "sans-serif",
    "IBM Plex Sans": "sans-serif",
    "Public Sans": "sans-serif",
    "Noto Sans": "sans-serif",
    "PT Sans": "sans-serif",
    "Cabin": "sans-serif",
    "Oxygen": "sans-serif",
    "Jost": "sans-serif",
    "Assistant": "sans-serif",
    "Hind": "sans-serif",
    "Titillium Web": "sans-serif",
    "Archivo": "sans-serif",
    "Figtree": "sans-serif",
    "Outfit": "sans-serif",
    "Space Grotesk": "sans-serif",
    "Urbanist": "sans-serif",
    "Sora": "sans-serif",
    "Lexend": "sans-serif",

    "Playfair Display": "serif",
    "Merriweather": "serif",
    "Lora": "serif",
    "PT Serif": "serif",
    "Noto Serif": "serif",
    "Source Serif Pro": "serif",
    "Source Serif 4": "serif",
    "Crimson Text": "serif",
    "Crimson Pro": "serif",
    "EB Garamond": "serif",
    "Libre Baskerville": "serif",
    "Cormorant": "serif",
    "Cormorant Garamond": "serif",
    "Bitter": "serif",
    "Vollkorn": "serif",
    "Domine": "serif",
    "Spectral": "serif",
    "Cardo": "serif",
    "Alegreya": "serif",
    "IBM Plex Serif": "serif",
    "Frank Ruhl Libre": "serif",
    "Gelasio": "serif",
    "Literata": "serif",
    "Newsreader": "serif",

    "Roboto Slab": "slab-serif",
    "Josefin Slab": "slab-serif",
    "Zilla Slab": "slab-serif",
    "Arvo": "slab-serif",
    "Rokkitt": "slab-serif",
    "Aleo": "slab-serif",
    "Bitter Slab": "slab-serif",
    "Slabo 27px": "slab-serif",
    "Roboto Slab Condensed": "slab-serif",
    "Bevan": "slab-serif",
    "Trocchi": "slab-serif",
    "Kreon": "slab-serif",

    "Oswald": "display",
    "Anton": "display",
    "Bebas Neue": "display",
    "Abril Fatface": "display",
    "Lobster": "display",
    "Pacifico": "display",
    "Righteous": "display",
    "Comfortaa": "display",
    "Fjalla One": "display",
    "Alfa Slab One": "display",
    "Passion One": "display",
    "Bungee": "display",
    "Staatliches": "display",
    "Baloo 2": "display",
    "Yeseva One": "display",
    "Bangers": "display",
    "Monoton": "display",
    "Shrikhand": "display",

    "Roboto Mono": "monospace",
    "Source Code Pro": "monospace",
    "IBM Plex Mono": "monospace",
    "JetBrains Mono": "monospace",
    "Space Mono": "monospace",
    "Inconsolata": "monospace",
    "Fira Code": "monospace",
    "Courier Prime": "monospace",
    "PT Mono": "monospace",
    "Noto Sans Mono": "monospace",
    "DM Mono": "monospace",
    "Major Mono Display": "monospace",
    "Overpass Mono": "monospace",

    # Common system fonts, useful for local validation/spot-checks even though
    # they aren't part of the Google Fonts download set.
    "Georgia": "serif",
    "Times New Roman": "serif",
    "Cambria": "serif",
    "Garamond": "serif",
    "Book Antiqua": "serif",
    "Arial": "sans-serif",
    "Helvetica": "sans-serif",
    "Calibri": "sans-serif",
    "Verdana": "sans-serif",
    "Tahoma": "sans-serif",
    "Segoe UI": "sans-serif",
    "Consolas": "monospace",
    "Courier New": "monospace",
    # Cycle 9 additions (sans-serif)
    "Albert Sans": "sans-serif",
    "Asap": "sans-serif",
    "Assistant": "sans-serif",
    "Be Vietnam Pro": "sans-serif",
    "Catamaran": "sans-serif",
    "Chivo": "sans-serif",
    "Epilogue": "sans-serif",
    "Exo 2": "sans-serif",
    "Fira Sans": "sans-serif",
    "Heebo": "sans-serif",
    "Hind": "sans-serif",
    "Josefin Sans": "sans-serif",
    "Kanit": "sans-serif",
    "Maven Pro": "sans-serif",
    "Mulish": "sans-serif",
    "Noto Sans": "sans-serif",
    "Overpass": "sans-serif",
    "Plus Jakarta Sans": "sans-serif",
    "Prompt": "sans-serif",
    "Quicksand": "sans-serif",
    "Rajdhani": "sans-serif",
    "Red Hat Display": "sans-serif",
    "Red Hat Text": "sans-serif",
    "Saira": "sans-serif",
    "Signika": "sans-serif",
    "Titillium Web": "sans-serif",
    "Varela Round": "sans-serif",

    # Cycle 9 additions (serif)
    "Cinzel": "serif",
    "Faustina": "serif",
    "Marcellus": "serif",
    "Neuton": "serif",
    "Noto Serif": "serif",
    "Old Standard TT": "serif",
    "Petrona": "serif",
    "Prata": "serif",
    "Rasa": "serif",
    "Sorts Mill Goudy": "serif",
    "Vidaloka": "serif",

    # Cycle 9 additions (slab-serif)
    "Bree Serif": "slab-serif",
    "Podkova": "slab-serif",
    "Rosarivo": "slab-serif",
    "Sanchez": "slab-serif",
    "Trirong": "slab-serif",

    # Cycle 9 additions (display)
    "Amatic SC": "display",
    "Architects Daughter": "display",
    "Bowlby One": "display",
    "Caveat": "display",
    "Chewy": "display",
    "Concert One": "display",
    "Dancing Script": "display",
    "Fredoka": "display",
    "Gochi Hand": "display",
    "Great Vibes": "display",
    "Indie Flower": "display",
    "Kalam": "display",
    "Lobster Two": "display",
    "Luckiest Guy": "display",
    "Patrick Hand": "display",
    "Permanent Marker": "display",
    "Sacramento": "display",
    "Satisfy": "display",
    "Shadows Into Light": "display",
    "Sniglet": "display",
    "Special Elite": "display",
    "Titan One": "display",

    # Cycle 9 additions (monospace)
    "Anonymous Pro": "monospace",
    "B612 Mono": "monospace",
    "Cousine": "monospace",
    "Cutive Mono": "monospace",
    "Nova Mono": "monospace",
    "Share Tech Mono": "monospace",
    "Ubuntu Mono": "monospace",
    "VT323": "monospace",
}


def category_for(family_name: str) -> str:
    """Best-effort category lookup; falls back to 'unknown' rather than guessing."""
    if family_name in FAMILY_CATEGORY:
        return FAMILY_CATEGORY[family_name]
    for known, cat in FAMILY_CATEGORY.items():
        if known.lower() == family_name.lower():
            return cat
    return "unknown"
