"""EVOLUTION_LOG cycle 6: a single, self-contained static HTML gallery
showing off the tool's best pairings across every font category. No server
required — images are embedded as base64 so the file can be opened, emailed,
or shared on its own.
"""

import base64
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from recommend import recommend_pairings, _connect, DB_PATH
from render import render_pairing, OUTPUT_DIR

GALLERY_PATH = os.path.join(OUTPUT_DIR, "gallery.html")

# One representative, well-known font per category, present in the DB.
SHOWCASE_FONTS = [
    ("Playfair Display", "serif"),
    ("Montserrat", "sans-serif"),
    ("Zilla Slab", "slab-serif"),
    ("Anton", "display"),
    ("JetBrains Mono", "monospace"),
]

TOP_N = 3

CSS = """
:root {
  --bg: #0b0b0e;
  --card-bg: #16161c;
  --border: #26262f;
  --text: #f2f2f5;
  --muted: #9a9aa5;
  --accent: #7c9dff;
}
* { box-sizing: border-box; }
body {
  margin: 0;
  padding: 48px 24px;
  background: var(--bg);
  color: var(--text);
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", system-ui, sans-serif;
}
.wrap { max-width: 1100px; margin: 0 auto; }
header { margin-bottom: 40px; }
header h1 { font-size: 28px; margin: 0 0 8px; }
header p { color: var(--muted); margin: 0; font-size: 15px; line-height: 1.5; }
.category-section { margin-bottom: 56px; }
.category-title {
  display: flex; align-items: baseline; gap: 10px;
  border-bottom: 1px solid var(--border);
  padding-bottom: 10px; margin-bottom: 20px;
}
.category-title h2 { font-size: 18px; margin: 0; }
.category-title .badge {
  font-size: 11px; text-transform: uppercase; letter-spacing: 0.06em;
  color: var(--accent); border: 1px solid var(--accent);
  border-radius: 999px; padding: 2px 10px;
}
.cards { display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 20px; }
.card {
  background: var(--card-bg); border: 1px solid var(--border); border-radius: 10px;
  overflow: hidden;
}
.card img { width: 100%; display: block; background: #fff; }
.card-meta { padding: 14px 16px; }
.card-meta .score {
  font-size: 13px; font-weight: 600; color: var(--accent); margin-bottom: 4px;
}
.card-meta .names { font-size: 14px; margin-bottom: 6px; }
.card-meta .explanation { font-size: 12px; color: var(--muted); line-height: 1.4; }
footer { color: var(--muted); font-size: 12px; margin-top: 40px; text-align: center; }
"""


def _embed_image(path: str) -> str:
    with open(path, "rb") as f:
        data = base64.b64encode(f.read()).decode("ascii")
    return f"data:image/png;base64,{data}"


def generate_gallery(showcase_fonts=SHOWCASE_FONTS, top_n=TOP_N, out_path=GALLERY_PATH):
    conn = _connect(DB_PATH)
    total_fonts = conn.execute("SELECT COUNT(*) FROM fonts").fetchone()[0]
    conn.close()

    sections = []
    for font_name, category in showcase_fonts:
        recs = recommend_pairings(font_name, top_n=top_n)
        cards = []
        for r in recs:
            image_path = render_pairing(font_name, r["family_name"], out_dir=OUTPUT_DIR)
            embedded = _embed_image(image_path)
            cards.append(f"""
        <div class="card">
          <img src="{embedded}" alt="{font_name} paired with {r['family_name']}">
          <div class="card-meta">
            <div class="score">Score: {r['score']:.2f}</div>
            <div class="names">{font_name} + {r['family_name']} <span style="color:var(--muted)">({r['category']})</span></div>
            <div class="explanation">{r['explanation']}</div>
          </div>
        </div>""")

        sections.append(f"""
    <section class="category-section">
      <div class="category-title">
        <h2>{font_name}</h2>
        <span class="badge">{category}</span>
      </div>
      <div class="cards">{''.join(cards)}
      </div>
    </section>""")

    html = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Font Pairing Gallery</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>{CSS}</style>
</head>
<body>
  <div class="wrap">
    <header>
      <h1>Font Pairing Gallery</h1>
      <p>Best-scoring pairings for one representative font per category, out of {total_fonts} fonts
      in the database. Every score comes from a transparent, hand-designed weighted-sum function over
      measured typographic properties &mdash; no ratings, no black-box model. Generated by
      src/generate_gallery.py.</p>
    </header>
    {''.join(sections)}
    <footer>Font Pairing &amp; Typography Analysis Tool &mdash; self-contained, no external assets.</footer>
  </div>
</body>
</html>
"""

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(html)
    return out_path


if __name__ == "__main__":
    path = generate_gallery()
    print(f"Gallery written to {path}")
